kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: prometheus-server
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: 0
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-server-conf
            defaultMode: 420
        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: prometheus-storage-volume
      containers:
        - name: prometheus
          image: 'prom/prometheus:latest'
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus/'
          ports:
            - containerPort: 9090
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      restartPolicy: Always
